---
# Source: statuspage/templates/externalsecret.yaml
# templates/externalsecret.yaml
# The secret key for django
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: django-secret-sync
spec:
  refreshInterval: 1h # Check if the secret was changed in AWS every hour
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: release-name-statuspage-secrets # Name of the secret in K8s
    creationPolicy: Owner
  data:
  - secretKey: SECRET_KEY # The key inside of the K8s secret
    remoteRef:
      key: Nadav-Statuspage-Project-DEV-django-secret-dev # The name of the secret in AWS
  - secretKey: DB_PASSWORD
    remoteRef:
      key: Nadav-Statuspage-Project-DEV-db-password-dev
  - secretKey: ADMIN_PASSWORD
    remoteRef:
      key: Nadav-Statuspage-Project-DEV-admin-credentials-dev
