apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "statuspage.fullname" . }}-config
data:
  # RDS
  DB_HOST: {{ .Values.database.host | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  DB_PORT: {{ .Values.database.port | default 5432 | quote }}

  # Redis
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | default 6379 | quote }}

  # Storage (S3)
  AWS_STORAGE_BUCKET_NAME: {{ .Values.config.s3BucketName | quote }}
  AWS_S3_REGION_NAME: {{ .Values.config.awsRegion | quote }}
  USE_S3: {{ .Values.config.useS3 | quote }}

  # Django configurations
  DJANGO_DEBUG: {{ .Values.config.djangoDebug | quote }}
  ALLOWED_HOSTS: {{ .Values.config.allowedHosts | quote }}