# templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: django-secret-sync
spec:
  refreshInterval: 1h # Check if the secret was changed in AWS every hour
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ include "statuspage.fullname" . }}-secrets # Name of the secret in K8s
    creationPolicy: Owner
  data:
  - secretKey: SECRET_KEY # The key inside of the K8s secret
    remoteRef:
      key: {{ .Values.secrets.djangoSecretName }} # The name of the secret in AWS
  - secretKey: DB_PASSWORD
    remoteRef:
      key: {{ .Values.secrets.dbPasswordSecretName }}
  - secretKey: ADMIN_PASSWORD
    remoteRef:
      key: {{ .Values.secrets.djangoAdminSecretName }}