apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: django-secret-sync
spec:
  refreshInterval: 1h # Check if the secret was changed in AWS every hour
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: statuspage-secrets # Name of the secret in K8s
    creationPolicy: Owner
  data:
  {{- $cm := lookup "v1" "ConfigMap" .Release.Namespace "statuspage-app-config" -}}
  {{- if $cm }}
  - secretKey: SECRET_KEY
    remoteRef:
      key: {{ index $cm.data "DJANGO_SECRET_NAME" | quote }}
  - secretKey: DB_PASSWORD
    remoteRef:
      key: {{ index $cm.data "DB_PASSWORD_SECRET_NAME" | quote }}
  - secretKey: ADMIN_PASSWORD
    remoteRef:
      key: {{ index $cm.data "DJANGO_ADMIN_SECRET_NAME" | quote }}
  {{- else }}
  # Fallback gracefully if ConfigMap is entirely absent during a dry-run
  - secretKey: SECRET_KEY
    remoteRef:
      key: "pending-secretmanager-creation"
  - secretKey: DB_PASSWORD
    remoteRef:
      key: "pending-secretmanager-creation"
  - secretKey: ADMIN_PASSWORD
    remoteRef:
      key: "pending-secretmanager-creation"
  {{- end }}