apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "statuspage.fullname" . }}-github-auth
  namespace: statuspage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: statuspage-github-secret
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: nadav-statuspage/github-auth
        property: STATUSPAGE_AUTH_GITHUB_CLIENT_ID
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: nadav-statuspage/github-auth
        property: STATUSPAGE_AUTH_GITHUB_CLIENT_SECRET
    - secretKey: ALLOWED_GITHUB_USERS
      remoteRef:
        key: nadav-statuspage/github-auth
        property: ALLOWED_GITHUB_USERS
