apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "statuspage.fullname" . }}
  labels:
    {{- include "statuspage.labels" . | nindent 4 }}
  annotations:
    # This tells K8s to use ALB
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: '8000'
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "statuspage.fullname" . }}-web
                port: 
                  number: 80